SELECT CEIL(AVG(Salary) - AVG(REPLACE(Salary, '0', '')))
FROM EMPLOYEES;

SELECT ROUND(AVG(LAT_N), 4)
FROM (
    SELECT LAT_N
    FROM STATION
    ORDER BY LAT_N
    LIMIT 2 - (SELECT COUNT(*) FROM STATION) % 2
    OFFSET (SELECT (COUNT(*) - 1) / 2 FROM STATION)
) AS median; 